site_name: i2pd documentation
site_url: https://i2pd.readthedocs.io
site_description: i2pd documentation
site_author: PurpleI2P Team

repo_url: https://github.com/PurpleI2P/i2pd_docs_en

nav:
- 主页: index.md
- 用户指南:
    - 安装: user-guide/install.md
    - 运行: user-guide/run.md
    - 配置: user-guide/configuration.md
    - I2P 隧道配置: user-guide/tunnels.md
    - 家族配置: user-guide/family.md
    - 问与答: user-guide/FAQ.md
- 操作方法/教程:
    - 匿名网站: tutorials/http.md
    - 匿名 IRC 聊天: tutorials/irc.md
    - 去中心化即时通讯 (XMPP, 又称之为 Jabber): tutorials/xmpp.md
    - 文件共享: tutorials/filesharing.md
    - 使用 RetroShare 搭配 i2pd: tutorials/retroshare.md
    - 无需 Reseed 服务器的引导: tutorials/floodfill-bootstrap.md
    - 仅通过 Yggdrasil 的路由器配置: tutorials/yggdrasil-only-mode.md
- 开发者部分:
    - 从源代码构建:
        - 构建要求: devs/building/requirements.md
        - Unix: devs/building/unix.md
        - Windows: devs/building/windows.md
        - Android: devs/building/android.md
        - 交叉编译: devs/building/cross.md
        - iOS: devs/building/ios.md
        - GUI 应用: devs/building/qt-desktop-gui.md
    - API:
        - 为你的项目选择 API: devs/api/index.md
        - SAM: devs/api/SAM.md
        - BOB: devs/api/BOB.md
        - I2CP: devs/api/I2CP.md
        - I2PControl: devs/api/I2PControl.md
        - libi2pd: devs/api/libi2pd.md
    - i2pd 对 I2P 协议的特定更改: devs/i2pd-specifics.md
    - 开发 i2pd: devs/hacking.md
- 关于:
    - 社区: about/community.md
    - 历史: about/history.md
    - 许可证: about/license.md
    - 贡献: about/contributing.md

copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>, Maintained by the PurpleI2P team
theme: readthedocs


markdown_extensions:
  - toc:
      permalink: true
